<a href="https://colab.research.google.com/github/NagillaSannidhi/python/blob/main/Day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(20,60,15)

In [ ]:
a

array([53, 49, 38, 52, 41, 42, 32, 58, 30, 43, 51, 56, 44, 52, 40])

In [ ]:
a[-5]

51

In [ ]:
a[8]

30

In [ ]:
a[-2:-9:-1]

array([52, 44, 56, 51, 43, 30, 58])

In [ ]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [ ]:
b[3]

array([46, 45, 52, 74, 65, 53, 60, 55])

In [ ]:
b[3,7]

55

In [ ]:
b[2:4]

array([[71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55]])